source ~/.tmux/vim.conf
source ~/.tmux/custom.conf
source ~/.tmux/tmuxline_base16_tomorrow_night.conf

set -g allow-rename off
set -g base-index 1
setw -g pane-base-index 1
set -g default-terminal "screen-256color"

# fix ssh agent when tmux is detached
set-option -ga update-environment 'SSH_AUTH_SOCK'

# Custom functions
bind -n C-Y run "tmux set-window-option synchronize-panes" \; display-message "Toggling synchronize-panes"

set-window-option -g mode-keys vi
