# This tmux statusbar config was created by tmuxline.vim
# on Wed, 28 Jun 2017

set -g status-bg "colour237"
set -g status-justify "left"
set -g status-left-length "100"
set -g status "on"
set -g status-right-length "100"
setw -g window-status-separator ""
set -g status-left "#[fg=colour237,bg=colour82] #S #[fg=colour82,bg=colour237,nobold,nounderscore,noitalics]"
#set -g status-right "#[fg=colour241,bg=colour237,nobold,nounderscore,noitalics]#[fg=colour253,bg=colour241] %Y-%m-%d  %H:%M #[fg=colour82,bg=colour241,nobold,nounderscore,noitalics]#[fg=colour237,bg=colour82] #h "
# With pomodoro
#%hidden pomodoro_status="#(pomodoro status)"
#%if "#{==:#(pomodoro_status),}"
#%hidden pomodoro_status=unset
#%endif
#%hidden pomodoro_color="#(pomodoro tmux-color --active color82)"
set -g status-right "#[fg=colour241,bg=colour237,nobold,nounderscore,noitalics]#[fg=color243,bg=#(pomodoro tmux-color --active color82 --done color1)]#(pomodoro status)#[fg=colour253,bg=colour241] %Y-%m-%d  %H:%M #[fg=colour82,bg=colour241,nobold,nounderscore,noitalics]#[fg=colour237,bg=colour82] #h "
setw -g window-status-format "#[fg=colour208,bg=colour237] #I #[fg=colour208,bg=colour237] #W "
setw -g window-status-current-format "#[fg=colour237,bg=colour241,nobold,nounderscore,noitalics]#[fg=colour253,bg=colour241] #I #[fg=colour253,bg=colour241] #W #[fg=colour241,bg=colour237,nobold,nounderscore,noitalics]"
